# coding: utf-8

"""
    NERM API

    The NERM API accesss and modifies resources in your environment.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.nerm.models.get_job_status200_response import GetJobStatus200Response

class TestGetJobStatus200Response(unittest.TestCase):
    """GetJobStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetJobStatus200Response:
        """Test GetJobStatus200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetJobStatus200Response`
        """
        model = GetJobStatus200Response()
        if include_optional:
            return GetJobStatus200Response(
                uid = '',
                status = 'complete',
                job_type = 'import',
                job_data = [
                    sailpoint.nerm.models.get_job_status_200_response_job_data_inner.getJobStatus_200_response_job_data_inner(
                        user_id = '', 
                        manager_id = '', 
                        errors = [
                            'Validation error for record in job'
                            ], )
                    ]
            )
        else:
            return GetJobStatus200Response(
        )
        """

    def testGetJobStatus200Response(self):
        """Test GetJobStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
