# coding: utf-8

"""
    Identity Security Cloud API - Search

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.search.models.search_post_v1401_response import SearchPostV1401Response

class TestSearchPostV1401Response(unittest.TestCase):
    """SearchPostV1401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchPostV1401Response:
        """Test SearchPostV1401Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchPostV1401Response`
        """
        model = SearchPostV1401Response()
        if include_optional:
            return SearchPostV1401Response(
                error = JWT validation failed: JWT is expired
            )
        else:
            return SearchPostV1401Response(
        )
        """

    def testSearchPostV1401Response(self):
        """Test SearchPostV1401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
