# coding: utf-8

"""
    Identity Security Cloud API - Connector Customizers

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.connector_customizers_v1.models.connectorcustomizerupdateresponse import Connectorcustomizerupdateresponse

class TestConnectorcustomizerupdateresponse(unittest.TestCase):
    """Connectorcustomizerupdateresponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Connectorcustomizerupdateresponse:
        """Test Connectorcustomizerupdateresponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Connectorcustomizerupdateresponse`
        """
        model = Connectorcustomizerupdateresponse()
        if include_optional:
            return Connectorcustomizerupdateresponse(
                id = 'b07dc46a-1498-4de8-bfbb-259a68e70c8a',
                name = 'connector-customizer-name',
                tenant_id = '2c91808568c529c60168cca6f90c1324',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                image_version = 1,
                image_id = '2c91808568c529c60168cca6f90c1324'
            )
        else:
            return Connectorcustomizerupdateresponse(
        )
        """

    def testConnectorcustomizerupdateresponse(self):
        """Test Connectorcustomizerupdateresponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
