# coding: utf-8

"""
    Identity Security Cloud API - Role Insights

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.role_insights_v1.api.role_insights_v1_api import RoleInsightsV1Api


class TestRoleInsightsV1Api(unittest.TestCase):
    """RoleInsightsV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = RoleInsightsV1Api()

    def tearDown(self) -> None:
        pass

    def test_create_role_insight_requests_v1(self) -> None:
        """Test case for create_role_insight_requests_v1

        Generate insights for roles
        """
        pass

    def test_download_role_insights_entitlements_changes_v1(self) -> None:
        """Test case for download_role_insights_entitlements_changes_v1

        Download entitlement insights for a role
        """
        pass

    def test_get_entitlement_changes_identities_v1(self) -> None:
        """Test case for get_entitlement_changes_identities_v1

        Get identities for a suggested entitlement (for a role)
        """
        pass

    def test_get_role_insight_v1(self) -> None:
        """Test case for get_role_insight_v1

        Get a single role insight
        """
        pass

    def test_get_role_insights_current_entitlements_v1(self) -> None:
        """Test case for get_role_insights_current_entitlements_v1

        Get current entitlement for a role
        """
        pass

    def test_get_role_insights_entitlements_changes_v1(self) -> None:
        """Test case for get_role_insights_entitlements_changes_v1

        Get entitlement insights for a role
        """
        pass

    def test_get_role_insights_requests_v1(self) -> None:
        """Test case for get_role_insights_requests_v1

        Returns metadata from prior request.
        """
        pass

    def test_get_role_insights_summary_v1(self) -> None:
        """Test case for get_role_insights_summary_v1

        Get role insights summary information
        """
        pass

    def test_get_role_insights_v1(self) -> None:
        """Test case for get_role_insights_v1

        Get role insights
        """
        pass


if __name__ == '__main__':
    unittest.main()
