# coding: utf-8

"""
    Identity Security Cloud Beta API

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: 3.1.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.beta.models.connector_rule_create_request import ConnectorRuleCreateRequest

class TestConnectorRuleCreateRequest(unittest.TestCase):
    """ConnectorRuleCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectorRuleCreateRequest:
        """Test ConnectorRuleCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectorRuleCreateRequest`
        """
        model = ConnectorRuleCreateRequest()
        if include_optional:
            return ConnectorRuleCreateRequest(
                name = 'WebServiceBeforeOperationRule',
                description = 'This rule does that',
                type = 'BuildMap',
                signature = sailpoint.beta.models.connector_rule_create_request_signature.ConnectorRuleCreateRequest_signature(
                    input = [
                        sailpoint.beta.models.argument.Argument(
                            name = 'firstName', 
                            description = 'the first name of the identity', 
                            type = 'String', )
                        ], 
                    output = sailpoint.beta.models.argument.Argument(
                        name = 'firstName', 
                        description = 'the first name of the identity', 
                        type = 'String', ), ),
                source_code = sailpoint.beta.models.source_code.SourceCode(
                    version = '1.0', 
                    script = 'return "Mr. " + firstName;', ),
                attributes = {}
            )
        else:
            return ConnectorRuleCreateRequest(
                name = 'WebServiceBeforeOperationRule',
                type = 'BuildMap',
                source_code = sailpoint.beta.models.source_code.SourceCode(
                    version = '1.0', 
                    script = 'return "Mr. " + firstName;', ),
        )
        """

    def testConnectorRuleCreateRequest(self):
        """Test ConnectorRuleCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
