# coding: utf-8

"""
    Identity Security Cloud Beta API

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: 3.1.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.beta.models.sod_violation_context2_conflicting_access_criteria import SodViolationContext2ConflictingAccessCriteria

class TestSodViolationContext2ConflictingAccessCriteria(unittest.TestCase):
    """SodViolationContext2ConflictingAccessCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodViolationContext2ConflictingAccessCriteria:
        """Test SodViolationContext2ConflictingAccessCriteria
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodViolationContext2ConflictingAccessCriteria`
        """
        model = SodViolationContext2ConflictingAccessCriteria()
        if include_optional:
            return SodViolationContext2ConflictingAccessCriteria(
                left_criteria = sailpoint.beta.models.sod_violation_context_2_conflicting_access_criteria_left_criteria.SodViolationContext_2_conflictingAccessCriteria_leftCriteria(
                    criteria_list = [
                        sailpoint.beta.models.sod_exempt_criteria.Sod Exempt Criteria(
                            existing = True, 
                            type = 'IDENTITY', 
                            id = '2c918085771e9d3301773b3cb66f6398', 
                            name = 'My HR Entitlement', )
                        ], ),
                right_criteria = sailpoint.beta.models.sod_violation_context_2_conflicting_access_criteria_left_criteria.SodViolationContext_2_conflictingAccessCriteria_leftCriteria(
                    criteria_list = [
                        sailpoint.beta.models.sod_exempt_criteria.Sod Exempt Criteria(
                            existing = True, 
                            type = 'IDENTITY', 
                            id = '2c918085771e9d3301773b3cb66f6398', 
                            name = 'My HR Entitlement', )
                        ], )
            )
        else:
            return SodViolationContext2ConflictingAccessCriteria(
        )
        """

    def testSodViolationContext2ConflictingAccessCriteria(self):
        """Test SodViolationContext2ConflictingAccessCriteria"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
