# coding: utf-8

"""
    Identity Security Cloud API - JIT Activations

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.jit_activations.models.jitactivationhistorydocument_summary import JitactivationhistorydocumentSummary

class TestJitactivationhistorydocumentSummary(unittest.TestCase):
    """JitactivationhistorydocumentSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JitactivationhistorydocumentSummary:
        """Test JitactivationhistorydocumentSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JitactivationhistorydocumentSummary`
        """
        model = JitactivationhistorydocumentSummary()
        if include_optional:
            return JitactivationhistorydocumentSummary(
                policy_matches = [
                    sailpoint.jit_activations.models.jitactivationhistorydocument_summary_policy_matches_inner.Jitactivationhistorydocument_summary_policyMatches_inner(
                        policy_id = '4d79eca9-8a77-4d06-8297-9be9868906f1', 
                        policy_name = 'Austin Engineering Policy', )
                    ],
                reauthentication = sailpoint.jit_activations.models.jitactivationhistorydocument_summary_reauthentication.Jitactivationhistorydocument_summary_reauthentication(
                    required = True, 
                    bypassed = False, ),
                justification = sailpoint.jit_activations.models.jitactivationhistorydocument_summary_justification.Jitactivationhistorydocument_summary_justification(
                    required = True, 
                    bypassed = False, ),
                service_now_ticket = sailpoint.jit_activations.models.jitactivationhistorydocument_summary_service_now_ticket.Jitactivationhistorydocument_summary_serviceNowTicket(
                    required = True, 
                    bypassed = False, 
                    ticket_reference = 'INC0012345', )
            )
        else:
            return JitactivationhistorydocumentSummary(
        )
        """

    def testJitactivationhistorydocumentSummary(self):
        """Test JitactivationhistorydocumentSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
