# coding: utf-8

"""
    Identity Security Cloud API - Intelligence

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.intelligence.models.intelmachineuserentitlement import Intelmachineuserentitlement

class TestIntelmachineuserentitlement(unittest.TestCase):
    """Intelmachineuserentitlement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Intelmachineuserentitlement:
        """Test Intelmachineuserentitlement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Intelmachineuserentitlement`
        """
        model = Intelmachineuserentitlement()
        if include_optional:
            return Intelmachineuserentitlement(
                source_id = '60de165099e649cb828553a5e8510fc4',
                entitlement_id = 'ent-001',
                display_name = 'Example_Entitlement',
                source = sailpoint.intelligence.models.intelmachinesourcewire.Intelmachinesourcewire(
                    id = '60de165099e649cb828553a5e8510fc4', 
                    name = 'Example Directory', 
                    type = 'DelimitedFile', )
            )
        else:
            return Intelmachineuserentitlement(
                source_id = '60de165099e649cb828553a5e8510fc4',
                entitlement_id = 'ent-001',
                display_name = 'Example_Entitlement',
        )
        """

    def testIntelmachineuserentitlement(self):
        """Test Intelmachineuserentitlement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
