# coding: utf-8

"""
    Identity Security Cloud API - Triggers

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.triggers_v1.models.basicauthconfig import Basicauthconfig

class TestBasicauthconfig(unittest.TestCase):
    """Basicauthconfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Basicauthconfig:
        """Test Basicauthconfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Basicauthconfig`
        """
        model = Basicauthconfig()
        if include_optional:
            return Basicauthconfig(
                user_name = 'user@example.com',
                password = ''
            )
        else:
            return Basicauthconfig(
        )
        """

    def testBasicauthconfig(self):
        """Test Basicauthconfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
