# coding: utf-8

"""
    Identity Security Cloud v2026 API

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v2026
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.v2026.models.get_stream200_response import GetStream200Response

class TestGetStream200Response(unittest.TestCase):
    """GetStream200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStream200Response:
        """Test GetStream200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStream200Response`
        """
        model = GetStream200Response()
        if include_optional:
            return GetStream200Response(
                stream_id = '550e8400-e29b-41d4-a716-446655440000',
                iss = 'https://tenant.sailpoint.com',
                aud = 'https://receiver.example.com',
                delivery = sailpoint.v2026.models.delivery_response.DeliveryResponse(
                    method = 'urn:ietf:rfc:8935', 
                    endpoint_url = 'https://receiver.example.com/ssf/events', ),
                events_supported = [https://schemas.openid.net/secevent/caep/event-type/{event-type}],
                events_requested = [https://schemas.openid.net/secevent/caep/event-type/{event-type}],
                events_delivered = [https://schemas.openid.net/secevent/caep/event-type/{event-type}],
                description = 'Production event stream',
                inactivity_timeout = 3600,
                min_verification_interval = 300
            )
        else:
            return GetStream200Response(
        )
        """

    def testGetStream200Response(self):
        """Test GetStream200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
