# coding: utf-8

"""
    Identity Security Cloud API - IAI Role Mining

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.iai_role_mining.models.roleminingpotentialroleapplication import Roleminingpotentialroleapplication

class TestRoleminingpotentialroleapplication(unittest.TestCase):
    """Roleminingpotentialroleapplication unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Roleminingpotentialroleapplication:
        """Test Roleminingpotentialroleapplication
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Roleminingpotentialroleapplication`
        """
        model = Roleminingpotentialroleapplication()
        if include_optional:
            return Roleminingpotentialroleapplication(
                id = '{"id":"2c9180877212632a017228d5a796292b"}',
                name = '{"name":"Slack"}'
            )
        else:
            return Roleminingpotentialroleapplication(
        )
        """

    def testRoleminingpotentialroleapplication(self):
        """Test Roleminingpotentialroleapplication"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
