# coding: utf-8

"""
    Identity Security Cloud API - Access Profiles

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.access_profiles_v1.models.list_access_profiles_v1429_response import ListAccessProfilesV1429Response

class TestListAccessProfilesV1429Response(unittest.TestCase):
    """ListAccessProfilesV1429Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAccessProfilesV1429Response:
        """Test ListAccessProfilesV1429Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAccessProfilesV1429Response`
        """
        model = ListAccessProfilesV1429Response()
        if include_optional:
            return ListAccessProfilesV1429Response(
                message =  Rate Limit Exceeded 
            )
        else:
            return ListAccessProfilesV1429Response(
        )
        """

    def testListAccessProfilesV1429Response(self):
        """Test ListAccessProfilesV1429Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
