# coding: utf-8

"""
    Identity Security Cloud API - Transforms

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.transforms.models.list_transforms_v1401_response import ListTransformsV1401Response

class TestListTransformsV1401Response(unittest.TestCase):
    """ListTransformsV1401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTransformsV1401Response:
        """Test ListTransformsV1401Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTransformsV1401Response`
        """
        model = ListTransformsV1401Response()
        if include_optional:
            return ListTransformsV1401Response(
                error = JWT validation failed: JWT is expired
            )
        else:
            return ListTransformsV1401Response(
        )
        """

    def testListTransformsV1401Response(self):
        """Test ListTransformsV1401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
