# coding: utf-8

"""
    Identity Security Cloud API - SP-Config

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.sp_config.models.import_sp_config_v1_request import ImportSpConfigV1Request

class TestImportSpConfigV1Request(unittest.TestCase):
    """ImportSpConfigV1Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportSpConfigV1Request:
        """Test ImportSpConfigV1Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportSpConfigV1Request`
        """
        model = ImportSpConfigV1Request()
        if include_optional:
            return ImportSpConfigV1Request(
                data = bytes(b'blah'),
                options = sailpoint.sp_config.models.import_options.Import Options(
                    exclude_types = [
                        'SOURCE'
                        ], 
                    include_types = [
                        'TRIGGER_SUBSCRIPTION'
                        ], 
                    object_options = {"TRIGGER_SUBSCRIPTION":{"includedIds":["be9e116d-08e1-49fc-ab7f-fa585e96c9e4"],"includedNames":["Test 2"]}}, 
                    default_references = [
                        'TRIGGER_SUBSCRIPTION'
                        ], 
                    exclude_backup = False, )
            )
        else:
            return ImportSpConfigV1Request(
                data = bytes(b'blah'),
        )
        """

    def testImportSpConfigV1Request(self):
        """Test ImportSpConfigV1Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
