# coding: utf-8

"""
    Identity Security Cloud API - Multi-Host Integration

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.multi_host_integration_v1.models.multihostintegrations_owner import MultihostintegrationsOwner

class TestMultihostintegrationsOwner(unittest.TestCase):
    """MultihostintegrationsOwner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultihostintegrationsOwner:
        """Test MultihostintegrationsOwner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultihostintegrationsOwner`
        """
        model = MultihostintegrationsOwner()
        if include_optional:
            return MultihostintegrationsOwner(
                type = 'IDENTITY',
                id = '2c91808568c529c60168cca6f90c1313',
                name = 'MyName'
            )
        else:
            return MultihostintegrationsOwner(
        )
        """

    def testMultihostintegrationsOwner(self):
        """Test MultihostintegrationsOwner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
