# coding: utf-8

"""
    Identity Security Cloud API - Governance Groups

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sailpoint.governance_groups.api.governance_groups_api import GovernanceGroupsApi


class TestGovernanceGroupsApi(unittest.TestCase):
    """GovernanceGroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GovernanceGroupsApi()

    def tearDown(self) -> None:
        pass

    def test_create_workgroup_v1(self) -> None:
        """Test case for create_workgroup_v1

        Create a new governance group.
        """
        pass

    def test_delete_workgroup_members_v1(self) -> None:
        """Test case for delete_workgroup_members_v1

        Remove members from governance group
        """
        pass

    def test_delete_workgroup_v1(self) -> None:
        """Test case for delete_workgroup_v1

        Delete a governance group
        """
        pass

    def test_delete_workgroups_in_bulk_v1(self) -> None:
        """Test case for delete_workgroups_in_bulk_v1

        Delete governance group(s)
        """
        pass

    def test_get_workgroup_v1(self) -> None:
        """Test case for get_workgroup_v1

        Get governance group by id
        """
        pass

    def test_list_connections_v1(self) -> None:
        """Test case for list_connections_v1

        List connections for governance group
        """
        pass

    def test_list_workgroup_members_v1(self) -> None:
        """Test case for list_workgroup_members_v1

        List governance group members
        """
        pass

    def test_list_workgroups_v1(self) -> None:
        """Test case for list_workgroups_v1

        List governance groups
        """
        pass

    def test_patch_workgroup_v1(self) -> None:
        """Test case for patch_workgroup_v1

        Patch a governance group
        """
        pass

    def test_update_workgroup_members_v1(self) -> None:
        """Test case for update_workgroup_members_v1

        Add members to governance group
        """
        pass


if __name__ == '__main__':
    unittest.main()
