# coding: utf-8

"""
    IdentityNow V3 API

    Use these APIs to interact with the IdentityNow platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
from sailpoint.v3.models.document_type import DocumentType
from sailpoint.v3.models.reference import Reference
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class EntitlementDocument(BaseModel):
    """
    Entitlement
    """

  # noqa: E501
    id: StrictStr = Field(
        description="The unique ID of the referenced object.")
    name: StrictStr = Field(
        description="The human readable name of the referenced object.")
    type: DocumentType = Field(alias="_type")
    description: Optional[StrictStr] = Field(
        default=None, description="A description of the entitlement")
    attribute: Optional[StrictStr] = Field(
        default=None, description="The name of the entitlement attribute")
    value: Optional[StrictStr] = Field(
        default=None, description="The value of the entitlement")
    modified: Optional[datetime] = Field(
        default=None, description="A date-time in ISO-8601 format")
    synced: Optional[datetime] = Field(
        default=None, description="A date-time in ISO-8601 format")
    display_name: Optional[StrictStr] = Field(
        default=None,
        description="The display name of the entitlement",
        alias="displayName")
    source: Optional[Reference] = None
    privileged: Optional[StrictBool] = None
    identity_count: Optional[StrictInt] = Field(default=None,
                                                alias="identityCount")
    tags: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = [
        "id", "name", "_type", "description", "attribute", "value", "modified",
        "synced", "displayName", "source", "privileged", "identityCount",
        "tags"
    ]

    model_config = {"populate_by_name": True, "validate_assignment": True}

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntitlementDocument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # set to None if modified (nullable) is None
        # and model_fields_set contains the field
        if self.modified is None and "modified" in self.model_fields_set:
            _dict['modified'] = None

        # set to None if synced (nullable) is None
        # and model_fields_set contains the field
        if self.synced is None and "synced" in self.model_fields_set:
            _dict['synced'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntitlementDocument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id":
            obj.get("id"),
            "name":
            obj.get("name"),
            "_type":
            obj.get("_type"),
            "description":
            obj.get("description"),
            "attribute":
            obj.get("attribute"),
            "value":
            obj.get("value"),
            "modified":
            obj.get("modified"),
            "synced":
            obj.get("synced"),
            "displayName":
            obj.get("displayName"),
            "source":
            Reference.from_dict(obj.get("source"))
            if obj.get("source") is not None else None,
            "privileged":
            obj.get("privileged"),
            "identityCount":
            obj.get("identityCount"),
            "tags":
            obj.get("tags")
        })
        return _obj
